webapp/courses/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # For administration of file upload exercises
    url(r'^file-upload-exercise-admin/(?P<exercise_id>\d+)$',
        views.file_upload_exercise_admin, name='file_upload_exercise_admin'),

    # For viewing and changing user information
    url(r'^answers/(?P<user>[^/]+)/(?P<answer_id>\d+)$',
        views.get_old_file_exercise_evaluation, name='get_old_file_exercise_evaluation'),
    url(r'^answers/(?P<user>[^/]+)/(?P<course>[^/]+)/(?P<instance>[^/]+)/(?P<exercise>[^/]+)',
        views.show_answers, name='show_answers'),
    url(r'^user/(?P<user_name>[^/]+)/$', views.user),
    url(r'^profile/$', views.user_profile),
    url(r'^profile/save/$', views.user_profile_save),

    # For calendar POST requests
    url(r'^calendar/(?P<calendar_id>\d+)/(?P<event_id>\d+)/$', views.calendar_post, name='calendar_post',),

    # Sandbox: admin view & answer for content pages without saved results
    url(r'^sandbox/(?P<content_slug>[^/]+)/$', views.sandboxed_content, name='sandbox',),
    url(r'^sandbox/(?P<content_slug>[^/]+)/check_sandboxed/$', views.check_answer_sandboxed, name='check_sandboxed'),
    
    # Help pages
    url(r'^help/$', views.help_list, name='help_list',),
    url(r'^help/markup/$', views.markup_help, name='markup_help',),
    url(r'^terms/$', views.terms, name='terms',),

    # Course front page and content views
    url(r'^(?P<course_slug>[^/]+)/$', views.course_instances, name='course_instances'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/$', views.course, name='course'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/$', views.content, name='content'),

    # Exercise sending for checking, progress and evaluation views
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/(?P<revision>(?:\d+|head))/check/$', views.check_answer, name='check'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/(?P<revision>(?:\d+|head))/progress/(?P<task_id>[^/]+)/$',
        views.check_progress, name='check_progress'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/(?P<revision>(?:\d+|head))/evaluation/(?P<task_id>[^/]+)/$',
        views.file_exercise_evaluation, name='file_exercise_evaluation'),
]

# For serving uploaded files on development server only:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/feedback/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^statistics/(?P<content_slug>[^/]+)/$', views.feedback_stats, name='statistics'),
    url(r'^(?P<content_slug>[^/]+)/(?P<feedback_slug>[^/]+)/receive-content/$', views.receive_content_feedback, name='receive-content-feedback'),
    url(r'^(?P<instance_slug>[^/]+)/(?P<feedback_slug>[^/]+)/receive-emb/$', views.receive_emb_feedback, name='receive-emb-feedback'),
]

webapp/lovelace/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# TODO: Design the url hierarchy from scratch
urlpatterns = [
    #url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('courses.urls', namespace='courses')),
]

webapp/stats/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^single-exercise/(?P<content_slug>[^/]+)/$', views.single_exercise, name='single_exercise'),
    url(r'^course-users/(?P<course_slug>[^/]+)/(?P<content_to_search>[^/]+)/(?P<year>\d{4})\-(?P<month>\d{2})\-(?P<day>\d{2})/$', views.course_users, name='course_users'),
    url(r'^all-exercises/(?P<course_name>[^/]+)/$', views.all_exercises, name='all_exercises'),
    url(r'^user-task/(?P<user_name>[^/]+)/(?P<task_name>.+)/$', views.user_task, name='user_task'),
    url(r'^users-all/$', views.users_all, name='users_all'),
    url(r'^users-course/(?P<course>[^/]+)/$', views.users_course, name='users_course'),
]

webapp/courses/forms.py
from django import forms

class TextfieldExerciseForm(forms.Form):
    pass

# http://jacobian.org/writing/dynamic-form-generation/
class MultipleChoiceExerciseForm(forms.Form):
    pass

class CheckboxExerciseForm(forms.Form):
    pass

class FileUploadExerciseForm(forms.Form):
    pass

class CodeInputExerciseForm(forms.Form):
    pass

class CodeReplaceExerciseForm(forms.Form):
    pass

webapp/courses/views.py
"""
Django views for rendering the course contents and checking exercises.
"""
import datetime
import json
from cgi import escape

from django.http import HttpResponse, JsonResponse, HttpResponseRedirect,\
    HttpResponseNotFound, HttpResponseForbidden, HttpResponseNotAllowed,\
    HttpResponseServerError
from django.template import Template, loader
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.contrib import messages

from reversion import revisions as reversion

from celery.result import AsyncResult
from courses.tasks import get_celery_worker_status

from courses.models import *
from courses.forms import *
from feedback.models import *

import courses.markupparser as markupparser
import courses.blockparser as blockparser

def cookie_law(view_func):
    """
    To comply with the European Union cookie law, display a warning about the
    site using cookies. When the user accepts cookies, set a session variable to
    disable the message.
    """
    def func_wrapper(request, *args, **kwargs):
        if "cookies_accepted" in request.COOKIES:
            if request.COOKIES["cookies_accepted"] == "1":
                request.session["cookies_accepted"] = True
        if request.session.get("cookies_accepted"):
            pass
        else:
            request.session["cookies_accepted"] = False
        return view_func(request, *args, **kwargs)
    return func_wrapper

@cookie_law
def index(request):
    course_list = Course.objects.all()

    t = loader.get_template("courses/index.html")
    c = {
        'course_list': course_list,
    }
    return HttpResponse(t.render(c, request))

@cookie_law
def course_instances(request, course_slug):
    return HttpResponse("here be instances for this course")

# TODO: A tool for locking the current revisions of embedded pages for
# course instances.

@cookie_law
def course(request, course_slug, instance_slug):
    try:
        course_obj = Course.objects.get(slug=course_slug)
    except Course.DoesNotExist:
        return HttpResponseNotFound("Course {} does not exist!".format(course_slug))

    try:
        instance_obj = CourseInstance.objects.get(slug=instance_slug)
    except CourseInstance.DoesNotExist:
        return HttpResponseNotFound("Course {} does not have an instance {}!".
                                    format(course_obj.name, instance_slug))

    frontpage = instance_obj.frontpage
    if frontpage:
        content_slug = frontpage.slug
        context = content(request, course_slug, instance_slug, content_slug, frontpage=True)
    else:
        context = {}

    context["course"] = course_obj
    context["instance"] = instance_obj

    contents = instance_obj.contents.filter(visible=True).order_by('ordinal_number')
    if len(contents) > 0:
        tree = []
        tree.append((mark_safe('>'), None, None, None))
        for content_ in contents:
            course_tree(tree, content_, request.user)
        tree.append((mark_safe('<'), None, None, None))
        context["content_tree"] = tree

    t = loader.get_template("courses/course.html")
    return HttpResponse(t.render(context, request))

def course_tree(tree, node, user):
    embedded_links = EmbeddedLink.objects.filter(parent=node.content.id)
    embedded_count = len(embedded_links)
    correct_embedded = 0
    
    evaluation = ""
    if user.is_authenticated():
        exercise = node.content
        evaluation = exercise.get_user_evaluation(exercise, user)

        if embedded_count > 0:
            for emb_exercise in embedded_links.values_list('embedded_page', flat=True):
                emb_exercise = ContentPage.objects.get(id=emb_exercise)
                print(emb_exercise.name)
                correct_embedded += 1 if emb_exercise.get_user_evaluation(emb_exercise, user) == "correct" else 0
    
    list_item = (node.content, evaluation, correct_embedded, embedded_count)
    
    if list_item not in tree:
        tree.append(list_item)

    children = ContentGraph.objects.filter(parentnode=node, visible=True).order_by('ordinal_number')
    if len(children) > 0:
        tree.append((mark_safe('>'), None, None, None))
        for child in children:
            course_tree(tree, child, user)
        tree.append((mark_safe('<'), None, None, None))

def check_answer_sandboxed(request, content_slug):
    """
    Saves and evaluates a user's answer to an exercise and sends the results
    back to the user in sanboxed mode.
    """

    course_slug = "sandbox"
    
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    user = request.user
    if not user.is_authenticated() or not user.is_active or not user.is_staff:
        return JsonResponse({
            'result': 'Only logged in admins can send their answers for evaluation!'
        })

    content = ContentPage.objects.get(slug=content_slug)
    
    user = request.user
    ip = request.META.get('REMOTE_ADDR')
    answer = request.POST
    files = request.FILES

    exercise = content.get_type_object()
    
    try:
        answer_object = exercise.save_answer(user, ip, answer, files)
    except InvalidExerciseAnswerException as e:
        return JsonResponse({
            'result': str(e)
        })
    evaluation = exercise.check_answer(user, ip, answer, files, answer_object)
    if not exercise.manually_evaluated:
        if exercise.content_type == "FILE_UPLOAD_EXERCISE":
            task_id = evaluation["task_id"]
            return check_progress(request, None, content_slug, task_id)
        exercise.save_evaluation(user, evaluation, answer_object)
        evaluation["manual"] = False
    else:
        evaluation["manual"] = True

    # TODO: Errors, hints, comments in JSON
    t = loader.get_template("courses/exercise-evaluation.html")
    return JsonResponse({
        'result': t.render(evaluation),
        'evaluation': evaluation.get("evaluation"),
    })

def check_answer(request, course_slug, instance_slug, content_slug, revision):
    """
    Saves and evaluates a user's answer to an exercise and sends the results
    back to the user.
    """
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    if not request.user.is_active:
        return JsonResponse({
            'result': 'Only logged in users can send their answers for evaluation!'
        })

    course = Course.objects.get(slug=course_slug)
    instance = CourseInstance.objects.get(slug=instance_slug)
    content = ContentPage.objects.get(slug=content_slug)
    # TODO: Ensure that the content revision really belongs to the course instance

    # TODO: The answer has to be linked to the revision the user is answering!

    # TODO: Resolve "head" revision to the newest revision
    if revision == "head":
        #reversion.
        pass

    # Check if a deadline exists and if it has already passed
    try:
        content_graph = instance.contents.filter(content=content).first()
    except ContentGraph.DoesNotExist as e:
        pass
    else:
        if content_graph is not None:
            if not content_graph.deadline or datetime.datetime.now() < content_graph.deadline:
                pass
            else:
                # TODO: Use a template!
                return JsonResponse({
                    'result': 'The deadline for this exercise (%s) has passed. Your answer will not be evaluated!' % (content_graph.deadline)
                })

    user = request.user
    ip = request.META.get('REMOTE_ADDR')
    answer = request.POST
    files = request.FILES

    exercise = content
    
    try:
        answer_object = exercise.save_answer(content, user, ip, answer, files, instance, revision)
    except InvalidExerciseAnswerException as e:
        return JsonResponse({
            'result': str(e)
        })
    evaluation = exercise.check_answer(content, user, ip, answer, files, answer_object, revision)
    if not exercise.manually_evaluated:
        if exercise.content_type == "FILE_UPLOAD_EXERCISE":
            task_id = evaluation["task_id"]
            return check_progress(request, course_slug, content_slug, task_id)
        exercise.save_evaluation(content, user, evaluation, answer_object)
        evaluation["manual"] = False
    else:
        evaluation["manual"] = True

    # TODO: Errors, hints, comments in JSON
    t = loader.get_template("courses/exercise-evaluation.html")
    return JsonResponse({
        'result': t.render(evaluation),
        'evaluation': evaluation.get("evaluation"),
    })

def check_progress(request, course_slug, instance_slug, content_slug, revision, task_id):
    # Based on https://djangosnippets.org/snippets/2898/
    # TODO: Check permissions
    task = AsyncResult(task_id)
    if task.ready():
        return file_exercise_evaluation(request, course_slug, content_slug, task_id, task)
    else:
        celery_status = get_celery_worker_status()
        if "errors" in celery_status:
            data = celery_status
        else:
            progress_url = reverse('courses:check_progress',
                                   kwargs={"course_slug": course_slug,
                                           "content_slug": content_slug,
                                           "task_id": task_id,})
            data = {"state": task.state, "metadata": task.info, "redirect": progress_url}
        return JsonResponse(data)

def file_exercise_evaluation(request, course_slug, instance_slug, content_slug, revision, task_id, task=None):
    if task is None:
        task = AsyncResult(task_id)
    evaluation_id = task.get()
    task.forget() # TODO: IMPORTANT! Also forget all the subtask results somehow? in tasks.py?
    evaluation_obj = Evaluation.objects.get(id=evaluation_id)

    # TODO: Nicer way to get the proper address!
    import redis
    r = redis.StrictRedis(host='localhost', port=6379, db=0)

webapp/courses/templates/courses/checkbox-exercise.html
{% extends 'courses/exercise.html' %}

{% block exercise-form %}
  {% for choice in choices %}
    <div class="input-label-container">
      {# TODO: The IDs need the revision info to prevent double IDs! #}
      {# The other exercise types probably need the same adjustemt -> implement in #}
      {# tandem with them. #}
      <input type="checkbox" name="{{ choice.id }}" id="cb-{{ choice.id }}" value="{{ choice.id }}" class="task_check"><label for="cb-{{ choice.id }}">{{ choice.answer }}</label>
    </div>
  {% endfor %}
{% endblock %}

webapp/courses/templates/courses/content-meta.html
{% load staticfiles %}
{% load i18n %}
<div class="task-meta-container" style="position:relative;width:0px;height:0px;">
  <div class="task-meta">
    {% if content.content_type != "LECTURE" and not sandboxed %}
      {% if evaluation == "unanswered" %}
        <img src="{% static 'courses/unanswered-96.png' %}" width="96" height="96" alt="?"
             title="{% trans 'You haven’t answered this exercise yet' %}" class="unanswered">
      {% elif evaluation == "incorrect" %}
        <img src="{% static 'courses/incorrect-96.png' %}" width="96" height="96" alt="✘"
             title="{% trans 'You have answered this exercise incorrectly' %}" class="incorrect">
      {% elif evaluation == "correct" %}
        <img src="{% static 'courses/correct-96.png' %}" width="96" height="96" alt="✔"
             title="{% trans 'You have answered this exercise correctly' %}" class="correct">
      {% endif %}

      {% comment %}
      <hr>
      Deadline: yyyy-mm-dd
      <hr>
      {% endcomment %}

      {% if not sandboxed %}
      <div><a href="{% url 'courses:show_answers' user.username course_slug instance_slug content.slug %}"
              title="{% trans 'View your previous answers' %}"><span class="answer-count">{{ answer_count }}</span> {% trans 'answers' %}</a></div>
      {% endif %}

      {% comment %}

      {# TODO: Feedback things #}
      <div class="give-feedback">
        <div class="good-or-bad">
          <span title="This exercise was good" style="cursor:pointer;">👍</span><span title="This exercise was bad" style="cursor:pointer;">👎</span>
        </div>
        <div class="five-stars">
          {% for i in "12345" %}<span title="{{ i }}" onmouseover="this.innerHTML='★';" onmouseout="this.innerHTML='☆';" style="cursor:pointer;">☆</span>{% endfor %}
        </div>
        <div class="open-feedback">
          <input type="text" title="Open feedback">{# TODO: onclick opens a bigger textarea for writing #}
        </div>
      </div>
          {% endcomment %}
      {% endif %}


    {% if user.is_active and user.is_staff %}
    <div class="admin-tools">
      <div><b>{% trans "Teacher’s tools" %}</b></div>
      <ul>
        <li><div><a href="{% url 'stats:single_exercise' content.slug %}">{% trans 'Statistics' %}</a></div></li>
        <li><div><a href="{% url 'feedback:statistics' content.slug %}">{% trans 'Feedback' %}</a></div></li>
        <li><div><a href="{{ content.get_admin_change_url }}">
              {% with type=content.get_human_readable_type %}
                {% if type == "lecture" %}
                  {% trans 'Edit this lecture' %}
                {% elif type == "textfield exercise" %}
                  {% trans 'Edit this textfield exercise' %}
                {% elif type == "multiple choice exercise" %}
                  {% trans 'Edit this multiple choice exercise' %}
                {% elif type == "checkbox exercise" %}
                  {% trans 'Edit this checkbox exercise' %}
                {% elif type == "file upload exercise" %}
                  {% trans 'Edit this file upload exericse' %}
                {% elif type == "code input exercise" %}
                  {% trans 'Edit this code input exercise' %}
                {% elif type == "code replace exercise" %}
                  {% trans 'Edit this code replace exercise' %}
                {% endif %}
              {% endwith %}
        </a></div></li>
        <li><div><a href="TODO">{% trans 'View reference answer' %}</a></div></li>
        <li><div><a href="{% url 'courses:sandbox' content.slug %}">{% trans 'View separately' %}</a></div></li>
      </ul>
    </div>
    {% endif %}
    
  </div>
</div>

webapp/courses/templates/courses/contentpage.html
{% extends 'courses/base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load course_tags %}

{% block page-title %}
{% if sandboxed %}
  {{ content.name }}
{% else %}
  {{ content.name }} – {{ course_name }}
{% endif %}
{% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'courses:index' %}">{% trans 'Courses' %}</a></li>
  {% if not sandboxed %}
  <div class="separator">»</div>
  <li><a href="{% url 'courses:course' course_slug instance_slug %}">{{ course_name }}&nbsp;/&nbsp;{{ instance_name }}</a></li>
  <div class="separator">»</div>
  <li><a href="{% url 'courses:content' course_slug instance_slug content.slug %}">{{ content.name }}</a></li>
  {% endif %}
{% endblock %}

{% block course-stats-link %}
  {% if not sandboxed %}
  <a href="{% url 'stats:users_course' course_slug %}">{% trans 'Course statistics' %}</a>
  {% endif %}
{% endblock %}

{% block revision-info %}
  {% if revision and revision > 0 and user.is_superuser %}
    <div class="revision-info">This is an old revision № {{ revision }} of this page!</div>
  {% endif %}
{% endblock %}

{% block page-content %}
{% if not content.is_answerable %}
  {% lecture %}
{% else %}
  {% if content.content_type == "MULTIPLE_CHOICE_EXERCISE" %}
    {% multiple_choice_exercise %}
  {% elif content.content_type == "CHECKBOX_EXERCISE" %}
    {% checkbox_exercise %}
  {% elif content.content_type == "TEXTFIELD_EXERCISE" %}
    {% textfield_exercise %}
  {% elif content.content_type == "FILE_UPLOAD_EXERCISE" %}
    {% file_upload_exercise %}
  {% endif %}
{% endif %}

{% endblock %}

webapp/courses/templates/courses/course.html
{% extends 'courses/base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block page-title %}{{ course.name }}{% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'courses:index' %}">{% trans 'Courses' %}</a></li>
  <div class="separator">»</div>
  <li><a href="{% url 'courses:course' course.slug instance.slug %}">{{ course.name }}&nbsp;/&nbsp;{{ instance.name }}</a></li>
{% endblock %}

{% block toc %}{% endblock %}

{% block course-stats-link %}<a href="{% url 'stats:users_course' course.slug %}">{% trans 'Course statistics' %}</a>{% endblock %}

{% block page-content %}
<h1 class="content-heading">{{ course.name }}<span id="{{ course.slug }}" class="anchor-offset"></span><a href="#{{ course.slug }}" class="permalink" title="Permalink to {{ course.name }}">&para;</a></h1>

{% if content_tree %}
  <div class="course-contents">
    <h2 class="content-heading">{% trans 'Course Contents' %}<span id="course-contents" class="anchor-offset"></span><a href="#course-contents" class="permalink" title="Permalink to Course Contents">&para;</a></h2>
    {% for list_direction, result, correct_emb, emb_count in content_tree %}
      {% if list_direction == '>' %}
        <ul>
          {% elif list_direction == '<' %}
        </ul>
      {% else %}
        <li>
          <a href="{% url 'courses:content' course.slug instance.slug list_direction.slug %}">{{ list_direction.name }}</a>
          {% if result and emb_count == 0 %}
            {% if result == 'unanswered' %}
              <img class="course-contents-result" src="{% static 'courses/unanswered-16.png' %}" alt="Unanswered">
            {% elif result == 'correct' %}
              <img class="course-contents-result" src="{% static 'courses/correct-16.png' %}" alt="Correctly answered">
            {% elif result == 'incorrect' %}
              <img class="course-contents-result" src="{% static 'courses/incorrect-16.png' %}" alt="Incorrectly answered">
            {% endif %}
          {% endif %}
          {% if emb_count > 0 %}
            <progress class="course-contents-progress" value="{{ correct_emb }}" max="{{ emb_count }}"
                      title="Completed {{ correct_emb }} / {{ emb_count }}">
          {% endif %}
        </li>
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

{% if rendered_content %}
  {{ rendered_content|safe }}
  {% if content.is_answerable %}
    {% include "courses/task.html" %}
  {% endif %}
{% endif %}
{% endblock %}

webapp/courses/templates/courses/exercise.html
{% load i18n %}
{% load course_tags %}

{% if user.is_active %}
  {% content_meta %}
{% endif %}

{% if rendered_content %}
  {{ rendered_content|safe }}
{% endif %}

{% if emb_content %}
  {% if revision and revision > 0 and user.is_superuser %}
    <div class="revision-info-embedded">This is an old revision № {{ revision }} of this embedded page!</div>
  {% endif %}
  <div>{{ emb_content|safe }}</div>
{% endif %}

  <div class="question">
    <div class="hints" style="display: none"></div>
    {% if sandboxed %}
    <form id="{{ content_slug }}-form" class="exercise-form" method="POST" enctype="multipart/form-data"
          action="{% url 'courses:check_sandboxed' content.slug %}">
    {% else %}
    <form id="{{ content_slug }}-form" class="exercise-form" method="POST" enctype="multipart/form-data"
          {% if revision %}action="{% url 'courses:check' course_slug instance_slug content.slug revision %}">
          {% else %}action="{% url 'courses:check' course_slug instance_slug content.slug "head" %}">{% endif %}
    {% endif %}

      {% csrf_token %}
      {% if question %}{{ question|safe }}{% endif %}
      
      {% block exercise-form %}
      {% endblock %}
            
      <input type="submit" name="submit" value="{% trans 'Send answer' %}">
      {% if not user.is_authenticated %}
        <div class="auth-warning">{% trans "Warning: You have not logged in. Your answer will not be saved." %}</div>
      {% endif %}
      {% if evaluation == "unanswered" %}
        <div class="answered-status"></div>
      {% elif evaluation == "incorrect" %}
        <div class="answered-status"><span class="incorrect">{% trans "You have previously answered this task incorrectly." %}</span></div>
      {% elif evaluation == "correct" %}
        <div class="answered-status"><span class="correct">{% trans "You have already answered this task correctly." %}</span></div>
      {% endif %}
    </form>
    <div class="error" style="display: none"></div>
    <div class="result" style="display: none"></div>
    <div class="comments" style="display: none"></div>
    <div class="file-result" style="display: none"></div>
  </div>

{% block feedback %}
  {% feedbacks %}
{% endblock %}

webapp/courses/templates/courses/user-exercise-answers.html
{% extends 'courses/base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load course_tags %}

{% block extra-static %}
<link rel="stylesheet" href="{% static 'courses/answers.css' %}">
<script src="{% static 'courses/answers.js' %}"></script>
{% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'courses:index' %}">{% trans 'Courses' %}</a></li>
  {% if not sandboxed %}
  <div class="separator">»</div>
  <li><a href="{% url 'courses:course' course_slug instance_slug %}">{{ course_name }}</a></li>
  {% endif %}
{% endblock %}

{% block page-content %}
<h1>Your answers to {{ exercise }}</h1>
<table class="fixed">
<colgroup>
  <col class="answer-date">
  <col class="answer">
  <col class="evaluation">
  <col class="permalink">
</colgroup>
<caption>{{ answers.count }} entered answers for this exercise</caption>
<thead>
  <tr>
    <th>Answer date</th>
    <th>Entered answer</th>
    <th>Evaluation</th>
    <th>Permalink</th>
  </tr>
</thead>
<tbody>
  {% for answer in answers %}
  <tr id="{{ answer.id }}">
    <td class="answer-date">{{ answer.answer_date|answer_date }}</td>
    <td class="answer">
      {% if answer.given_answer %}
        {{ answer.given_answer }}
      {% elif answer.chosen_answer %}
        {{ answer.chosen_answer }}
      {% elif answer.chosen_answers %}
        <ul>
          {% for chosen_answer in answer.chosen_answers.all %}
            <li>{{ chosen_answer }}</li>
          {% endfor %}
        </ul>
      {% elif answer.get_returned_files %}
        <ul>
          {% for file in answer.get_returned_files.items %}
            {% if file.1.1 == True %}
              <li>{{ file.0 }}</li>
            {% else %}
              <li><a class="fileview-link" href="" onclick="show_file(event, this);">{{ file.0 }}</a>
                <div class="popup"><pre class="fileview">{{ file.1.2|safe }}</pre></div>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}
    </td>
    <td class="evaluation {% if answer.evaluation.correct %}correct{% else %}incorrect{% endif %}">
      {% if answer.evaluation.correct %}
        <span title="Correct">✔</span>
      {% else %}
        <span title="Incorrect">✘</span>
      {% endif %}
      {% if answer.evaluation.test_results %}
        <a href="{% url 'courses:get_old_file_exercise_evaluation' user answer.id %}"
           onclick="show_results(event, this, 'results-{{ answer.id }}');">View results</a>
        <div class="popup"><div class="results-view" id="results-{{ answer.id }}"></div></div>
      {% endif %}
    </td>
    <td class="permalink"><a href="#{{ answer.id }}">&para;</a></td>
  </tr>
  {% endfor %}
</tbody>
</table>
{% endblock %}