webapp/courses/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # For administration of file upload exercises
    url(r'^file-upload-exercise-admin/(?P<exercise_id>\d+)$',
        views.file_upload_exercise_admin, name='file_upload_exercise_admin'),

    # For viewing and changing user information
    url(r'^answers/(?P<user>[^/]+)/(?P<answer_id>\d+)$',
        views.get_old_file_exercise_evaluation, name='get_old_file_exercise_evaluation'),
    url(r'^answers/(?P<user>[^/]+)/(?P<course>[^/]+)/(?P<instance>[^/]+)/(?P<exercise>[^/]+)',
        views.show_answers, name='show_answers'),
    url(r'^user/(?P<user_name>[^/]+)/$', views.user),
    url(r'^profile/$', views.user_profile),
    url(r'^profile/save/$', views.user_profile_save),

    # For calendar POST requests
    url(r'^calendar/(?P<calendar_id>\d+)/(?P<event_id>\d+)/$', views.calendar_post, name='calendar_post',),

    # Sandbox: admin view & answer for content pages without saved results
    url(r'^sandbox/(?P<content_slug>[^/]+)/$', views.sandboxed_content, name='sandbox',),
    url(r'^sandbox/(?P<content_slug>[^/]+)/check_sandboxed/$', views.check_answer_sandboxed, name='check_sandboxed'),
    
    # Help pages
    url(r'^help/$', views.help_list, name='help_list',),
    url(r'^help/markup/$', views.markup_help, name='markup_help',),
    url(r'^terms/$', views.terms, name='terms',),

    # Course front page and content views
    url(r'^(?P<course_slug>[^/]+)/$', views.course_instances, name='course_instances'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/$', views.course, name='course'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/$', views.content, name='content'),

    # Exercise sending for checking, progress and evaluation views
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/(?P<revision>(?:\d+|head))/check/$', views.check_answer, name='check'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/(?P<revision>(?:\d+|head))/progress/(?P<task_id>[^/]+)/$',
        views.check_progress, name='check_progress'),
    url(r'^(?P<course_slug>[^/]+)/(?P<instance_slug>[^/]+)/(?P<content_slug>[^/]+)/(?P<revision>(?:\d+|head))/evaluation/(?P<task_id>[^/]+)/$',
        views.file_exercise_evaluation, name='file_exercise_evaluation'),
]

# For serving uploaded files on development server only:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/feedback/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^statistics/(?P<content_slug>[^/]+)/$', views.feedback_stats, name='statistics'),
    url(r'^(?P<content_slug>[^/]+)/(?P<feedback_slug>[^/]+)/receive-content/$', views.receive_content_feedback, name='receive-content-feedback'),
    url(r'^(?P<instance_slug>[^/]+)/(?P<feedback_slug>[^/]+)/receive-emb/$', views.receive_emb_feedback, name='receive-emb-feedback'),
]

webapp/lovelace/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# TODO: Design the url hierarchy from scratch
urlpatterns = [
    #url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^stats/', include('stats.urls', namespace='stats')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('courses.urls', namespace='courses')),
]

webapp/stats/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^single-exercise/(?P<content_slug>[^/]+)/$', views.single_exercise, name='single_exercise'),
    url(r'^course-users/(?P<course_slug>[^/]+)/(?P<content_to_search>[^/]+)/(?P<year>\d{4})\-(?P<month>\d{2})\-(?P<day>\d{2})/$', views.course_users, name='course_users'),
    url(r'^all-exercises/(?P<course_name>[^/]+)/$', views.all_exercises, name='all_exercises'),
    url(r'^user-task/(?P<user_name>[^/]+)/(?P<task_name>.+)/$', views.user_task, name='user_task'),
    url(r'^users-all/$', views.users_all, name='users_all'),
    url(r'^users-course/(?P<course>[^/]+)/$', views.users_course, name='users_course'),
]

webapp/feedback/views.py
import feedback.models
import courses.models

from django.http import HttpResponse, HttpResponseNotFound, HttpResponseNotAllowed, \
    HttpResponseForbidden, JsonResponse
from django.template import loader

def textfield_feedback_stats(question, answers):
    return {
        "answers" : sorted(set(answers.values_list("answer", "answer_date")), key=lambda a: a[1], reverse=True),
        "answer_count": answers.count(),
        "user_count": len(set(answers.values_list("user")))
    }

def thumb_feedback_stats(question, answers):
    user_count = answers.count()
    thumbs_up = list(answers.values_list("thumb_up", flat=True)).count(True)
    thumbs_down = user_count - thumbs_up

    try:
        thumb_up_pct = round((thumbs_up / user_count) * 100, 2)
        thumb_down_pct = round((thumbs_down / user_count) * 100, 2)
    except ZeroDivisionError: # Catch zero division if there are no user answers
        thumb_up_pct = 0
        thumb_down_pct = 0

    return {
        "thumbs_up": thumbs_up, 
        "thumbs_down": thumbs_down,
        "thumb_up_pct": thumb_up_pct,
        "thumb_down_pct": thumb_down_pct,
        "user_count": user_count
    }

def star_feedback_stats(question, content):
    answers = question.get_latest_answers_by_content(content)
    user_count = answers.count()
    ratings = list(answers.values_list("rating", flat=True))
    rating_counts = [ratings.count(stars) for stars in range(1, 6)]

    rating_pcts = []
    for rcount in rating_counts:
        try:
            rating_pcts.append(round((rcount / user_count) * 100, 2))
        except ZeroDivisionError: # Catch zero division if there are no user answers
            rating_pcts.append(0.0)

    return {
        "rating_stats" : zip(rating_counts, rating_pcts),
        "user_count" : user_count
    }

def multiple_choice_feedback_stats(question, content):
    choices = list(question.get_choices())
    answers = question.get_latest_answers_by_content(content)
    user_count = answers.count()
    chosen_answers = list(answers.values_list("chosen_answer", flat=True))
    answer_counts = [chosen_answers.count(choice.id) for choice in choices]
        
    answer_pcts = []
    for ans_count in answer_counts:
        try:
            answer_pcts.append(round((ans_count / user_count) * 100, 2))
        except ZeroDivisionError: # Catch zero division if there are no user answers
            answer_pcts.append(0.0)

    return {
        "answer_stats" : zip(choices, answer_counts, answer_pcts),
        "user_count" : user_count
    }

def feedback_stats(request, content_slug):
    if not request.user.is_authenticated() or not request.user.is_active or not request.user.is_staff:
        return HttpResponseForbidden("Only logged in admins can view feedback statistics!")
    
    try:
        content = courses.models.ContentPage.objects.get(slug=content_slug)
    except courses.models.ContentPage.DoesNotExist:
        return HttpResponseNotFound("No content page {} found!".format(content_slug))

    questions = content.get_feedback_questions()
    ctx = {
        "content": content,
        "tasktype": content.get_human_readable_type(),
    }

    stats = {
        "textfield_feedback": [],
        "thumb_feedback" : [],
        "star_feedback" : [],
        "multiple_choice_feedback" : []
    }
    for question in questions:
        question_type = question.question_type
        question_ctx = {
            "question": question.question,
            "question_type": question_type,
            "question_slug": question.slug,
        }
        if question_type == "TEXTFIELD_FEEDBACK": 
            question_ctx.update(textfield_feedback_stats(question, question.get_answers_by_content(content)))
        elif question_type == "THUMB_FEEDBACK":
            question_ctx.update(thumb_feedback_stats(question, question.get_latest_answers_by_content(content)))
        elif question_type == "STAR_FEEDBACK":
            question_ctx.update(star_feedback_stats(question, question.get_latest_answers_by_content(content)))
        elif question_type == "MULTIPLE_CHOICE_FEEDBACK":
            question_ctx.update(multiple_choice_feedback_stats(question, question.get_latest_answers_by_content(content)))
        stats[question_type.lower()].append(question_ctx)
    ctx["feedback_stats"] = stats
    
    t = loader.get_template("feedback/feedback-stats.html")
    return HttpResponse(t.render(ctx, request))
   
def receive_content_feedback(request, content_slug, feedback_slug):
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    if not request.user.is_active:
        return JsonResponse({
            "result": "Only logged in users can send feedback!"
        })

    #TODO: Check that the user has successfully enrolled to the course instance.
    #TODO: Take the revision into account.
    
    content = courses.models.ContentPage.objects.get(slug=content_slug)
    cfq = feedback.models.ContentFeedbackQuestion.objects.get(slug=feedback_slug)

    user = request.user
    ip = request.META.get("REMOTE_ADDR")
    answer = request.POST

    question = cfq.get_type_object()
    
    try:
        answer_object = question.save_answer(content, user, ip, answer)
    except feedback.models.InvalidFeedbackAnswerException as e:
        return JsonResponse({
            "error": str(e)
        })

    return JsonResponse({
        "result": "Your feedback was received!"
    })

def receive_content_feedback(request, content_slug, feedback_slug):
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    if not request.user.is_active:
        return JsonResponse({
            "result": "Only logged in users can send feedback!"
        })

    #TODO: Check that the user has successfully enrolled to the course instance.
    #TODO: Take the revision into account.
    
    content = courses.models.ContentPage.objects.get(slug=content_slug)
    cfq = feedback.models.ContentFeedbackQuestion.objects.get(slug=feedback_slug)

    user = request.user
    ip = request.META.get("REMOTE_ADDR")
    answer = request.POST

    question = cfq.get_type_object()
    
    try:
        answer_object = question.save_answer(content, user, ip, answer)
    except feedback.models.InvalidFeedbackAnswerException as e:
        return JsonResponse({
            "error": str(e)
        })

    return JsonResponse({
        "result": "Your feedback was received!"
    })

def receive_emb_feedback(request, instance_slug, feedback_slug):
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"])

    if not request.user.is_active:
        return JsonResponse({
            "result": "Only logged in users can send feedback!"
        })

    #TODO: Check that the user has successfully enrolled to the course instance.
    #TODO: Take the revision into account.
    
    course_inst = courses.models.CourseInstance.objects.get(slug=instance_slug)
    efq = feedback.models.EmbeddedFeedbackQuestion.objects.get(slug=feedback_slug)

    user = request.user
    ip = request.META.get("REMOTE_ADDR")
    answer = request.POST

    question = efq.get_type_object()

    try:
        answer_object = question.save_answer(course_inst, user, ip, answer)
    except feedback.models.InvalidFeedbackAnswerException as e:
        return JsonResponse({
            "error": str(e)
        })

    return JsonResponse({
        "result": "Your feedback was received!"
    })

webapp/feedback/templates/feedback/feedback-question.html
{% load staticfiles %}
{% load i18n %}

{% if emb_feedback %}
  <div class="titled-feedback-container">
    <div class="feedback-container">
      <div class="titled-feedback-content">
        <h1 class="content-heading">{{ question }}<span id="give-feedback" class="anchor-offset"></span></h1>
        <div class="feedback">
          <div>{{ description|safe }}</div>
          {% if not sandboxed %}
            <form class="feedback-form" method="POST" enctype="multipart/form-data" action="{% url 'feedback:receive-emb-feedback' instance_slug feedback_slug %}">
          {% else %}
              <div class="feedback-disabled">Embedded feedback is disabled in sandbox</div>
          {% endif %}
{% else %}
          <div class="feedback">
            <div><span>{{ question }}</span></div>
            <form class="feedback-form" method="POST" enctype="multipart/form-data" action="{% url 'feedback:receive-content-feedback' content_slug feedback_slug %}">
{% endif %}
{% if not sandboxed or not emb_feedback %}  
  {% csrf_token %}
  {% block feedback-input %}
  {% endblock %}
            </form>
{% endif %}
<div class="feedback-received"></div>
<div class="feedback-error"></div>
{% if emb_feedback %}
          </div>
        </div>
      </div>
{% endif %}
    </div>

webapp/feedback/templates/feedback/feedback-stats.html
{% extends 'courses/base.html' %}

{% load feedback_tags %}
{% load staticfiles %}

{% block extra-static %}
  <link rel="stylesheet" href="{% static 'stats/style.css' %}">
  <script src="{% static 'stats/script.js' %}"></script>
{% endblock %}

{% block page-title %}
  Feedback – {{ content.name }}
{% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'courses:index' %}">Courses</a></li>
  <div class="separator">»</div>
  <li><a href="{% url 'courses:sandbox' content.slug %}">{{ content.name }}</a></li>
{% endblock %}

{% block page-content %}
  <h1 class="content-heading">Feedback on "{{ content.name }}"<span id="feedback" class="anchor-offset"></span></h1>
  
  {% for question_stats in feedback_stats.thumb_feedback %}
    <h2 class="content-heading">{{ question_stats.question }}<span id="{{ question_stats.question_slug }}_heading" class="anchor-offset"></span></h2>
    <div>This question has been answered by {{ question_stats.user_count }} user(s).</div>
    <table>
      <tr>
        <th>Thumbs up</th>
        <th>Thumbs down</th>
        <th>Thumbs up (&#37;)</th>
        <th>Thumbs down (&#37;)</th>
      </tr>
      <tr>
        <td>{{ question_stats.thumbs_up }}</td>
        <td>{{ question_stats.thumbs_down }}</td>
        <td>{{ question_stats.thumb_up_pct }}</td>
        <td>{{ question_stats.thumb_down_pct }}</td>
      </tr>
    </table>
  {% endfor %}
  
  {% for question_stats in feedback_stats.star_feedback %}
    <h2 class="content-heading">{{ question_stats.question }}<span id="{{ question_stats.question_slug }}_heading" class="anchor-offset"></span></h2>
    <div>This question has been answered by {{ question_stats.user_count }} user(s).</div>
    <table>
      <tr>
        <th>Rating</th>
        <th>Count</th>
        <th>(&#37;)</th>
      </tr>
      {% for rating_count, rating_pct in question_stats.rating_stats %}
        <tr>
          <td>{{ forloop.counter0|add:"1" }}</td>
          <td>{{ rating_count }}</td> 
          <td>{{ rating_pct }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endfor %}
  
  {% for question_stats in feedback_stats.multiple_choice_feedback %}
    <h2 class="content-heading">{{ question_stats.question }}<span id="{{ question_stats.question_slug }}_heading" class="anchor-offset"></span></h2>
    <div>This question has been answered by {{ question_stats.user_count }} user(s).</div>
    <table>
      <tr>
        <th>Choice</th>
        <th>Count</th>
        <th>(&#37;)</th>
      </tr>
      {% for choice, answer_count, answer_pct in question_stats.answer_stats %}
        <tr>
          <td>{{ choice }}</td>
          <td>{{ answer_count }}</td> 
          <td>{{ answer_pct }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endfor %}
  
  {% for question_stats in feedback_stats.textfield_feedback %}
    <h2 class="content-heading">{{ question_stats.question }}<span id="{{ question_stats.question_slug }}_heading" class="anchor-offset"></span></h2>
    <div>This question has been answered by {{ question_stats.user_count }} user(s).</div>
    <div>This question has been answered {{ question_stats.answer_count }} time(s).</div>
    {% if question_stats.answers %}
      <table id="{{ question_stats.question_slug }}_table" class="fixed">
        <colgroup>
          <col class="answer">
          <col class="latest">
        </colgroup>
        <tr>
          <th>User answer</th>
        {% sortable_table_header question_stats.question_slug "Latest" "1" %}
        </tr>
        {% for answer, dtime in question_stats.answers %}
          <tr>
            <td class="answer">{{ answer }}</td>          
            <td title="{{ dtime|date:'Y-m-d, H:i:s' }}">{{ dtime|answer_date }}</td>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  {% endfor %}
{% endblock %}

webapp/feedback/templates/feedback/feedbacks.html
{% load staticfiles %}
{% load i18n %}
{% load feedback_tags %}

{% with feedback_questions=content.get_feedback_questions %}
  {% if feedback_questions %}
    {% if emb_content %}
        <div class="feedback-container">
          <div class="feedback-header" onclick="show_feedbacks(this, 
                                          '{% trans 'Give feedback on this content' %}', 
                                          '{% trans 'Close feedback' %}', '{% static 'feedback/plus.png' %}', 
                                          '{% static 'feedback/minus.png' %}');">
            
            <img class="img-header" src="{% static 'feedback/plus.png' %}"><span>{% trans 'Give feedback on this content' %}</span>
          </div>
          <div class="exercise-feedback-content">
    {% else %}
            <div class="titled-feedback-container">
              <div class="feedback-container">
                <div class="titled-feedback-content">
                  <h1 class="content-heading">{% trans 'Give feedback on this content' %}<span id="give-feedback" class="anchor-offset"></span></h1>
    {% endif %}

    {% for question in feedback_questions %}
      {% if question.question_type == "THUMB_FEEDBACK" %}
        {% feedback_thumb question user content %}
      {% endif %}
    {% endfor %}

    {% for question in feedback_questions %}
      {% if question.question_type == "STAR_FEEDBACK" %}
        {% feedback_star question user content %}
      {% endif %}
    {% endfor %}

    {% for question in feedback_questions %}
      {% if question.question_type == "MULTIPLE_CHOICE_FEEDBACK" %}
        {% feedback_multiple_choice question user content %}
      {% endif %}
    {% endfor %}

    {% for question in feedback_questions %}
      {% if question.question_type == "TEXTFIELD_FEEDBACK" %}
        {% feedback_textfield question user content %}
      {% endif %}
    {% endfor %}
              </div>
            </div>
  {% endif %}
  {% if not emb_content %}
          </div>
  {% endif %}
{% endwith %}

webapp/feedback/templates/feedback/multiple-choice-feedback-question.html
{% extends 'feedback/feedback-question.html' %}

{% block feedback-input %}
  {% for choice in choices %}
    <div class="input-label-container">
      {% if user_answer.id == choice.id %}
        <input id="{{ radiobutton_id }}_box_{{ forloop.counter0 }}" name="choice" type="radio" value="{{ choice.id }}" onchange="select_choice(this);" checked="checked">
      {% else %}
        <input id="{{ radiobutton_id }}_box_{{ forloop.counter0 }}" name="choice" type="radio" value="{{ choice.id }}" onchange="select_choice(this);">
      {% endif %}
      <label for="{{ radiobutton_id }}_box_{{ forloop.counter0 }}">{{ choice.answer }}</label>
    </div>
  {% endfor %}
{% endblock %}

webapp/feedback/templates/feedback/sortable-table-header.html
{% load feedback_tags %}

<th>
  <div class="sortable-header">{{ header }}</div>
  <div>
    <button class="sort-desc" onclick="sortTable('{{ slug }}_table', {{ column }}, -1)">↑</button>
    <button class="sort-asc" onclick="sortTable('{{ slug }}_table', {{ column }}, 1)">↓</button>
  </div>
</th>

webapp/feedback/templates/feedback/star-feedback-question.html
{% extends 'feedback/feedback-question.html' %}

{% block feedback-input %}
  <div class="rating">
    <input id="{{ radiobutton_id }}_box_1" name="choice" type="radio" class="star-radio" onchange="select_stars(this, 1);" value="5">
    {% if user_answer == 5 %}
      <label for="{{ radiobutton_id }}_box_1" class="star-filled">☆</label>
    {% else %}
      <label for="{{ radiobutton_id }}_box_1" class="star-outline">☆</label>
    {% endif %}

    <input id="{{ radiobutton_id }}_box_2" name="choice" type="radio" class="star-radio" onchange="select_stars(this, 2);" value="4">
    {% if user_answer >= 4 %}
      <label for="{{ radiobutton_id }}_box_2" class="star-filled">☆</label>
    {% else %}
      <label for="{{ radiobutton_id }}_box_2" class="star-outline">☆</label>
    {% endif %}

    <input id="{{ radiobutton_id }}_box_3" name="choice" type="radio" class="star-radio" onchange="select_stars(this, 3);" value="3">
    {% if user_answer >= 3 %}
      <label for="{{ radiobutton_id }}_box_3" class="star-filled">☆</label>
    {% else %}
      <label for="{{ radiobutton_id }}_box_3" class="star-outline">☆</label>
    {% endif %}

    <input id="{{ radiobutton_id }}_box_4" name="choice" type="radio" class="star-radio" onchange="select_stars(this, 4);" value="2">
    {% if user_answer >= 2 %}
      <label for="{{ radiobutton_id }}_box_4" class="star-filled">☆</label>
    {% else %}
      <label for="{{ radiobutton_id }}_box_4" class="star-outline">☆</label>
    {% endif %}

    <input id="{{ radiobutton_id }}_box_5" name="choice" type="radio" class="star-radio" onchange="select_stars(this, 5);" value="1">
    {% if user_answer >= 1 %}
      <label for="{{ radiobutton_id }}_box_5" class="star-filled">☆</label>
    {% else %}
      <label for="{{ radiobutton_id }}_box_5" class="star-outline">☆</label>
    {% endif %}
  </div>
{% endblock %}

webapp/feedback/templates/feedback/textfield-feedback-question.html
{% extends 'feedback/feedback-question.html' %}
{% load i18n %}

{% block feedback-input %}
  <textarea name="text-feedback" class="feedback-textfield" placeholder="{% trans 'Enter your answer here' %}" rows="3"></textarea><br>
  <input class="send-feedback" type="submit" value="{% trans 'Send feedback' %}">
  {% if answered %}
    <div class="answered-status"><span class="feedback-answered">{% trans "You have already answered this feedback." %}</span></div>
  {% endif %}
{% endblock %}

webapp/feedback/templates/feedback/thumb-feedback-question.html
{% extends 'feedback/feedback-question.html' %}
{% load staticfiles %}

{% block feedback-input %}
  <label class="thumb-label">
    {% if user_answer == True %}
      <input type="radio" name="choice" class="thumb-radio" onchange="select_choice(this);" value="up" checked="checked">
    {% else %}
      <input type="radio" name="choice" class="thumb-radio" onchange="select_choice(this);" value="up">
    {% endif %}
    <img src="{% static 'feedback/thumbup.png' %}" alt="Thumb up">
    <img src="{% static 'feedback/thumbup_selected.png' %}" alt="Thumb up selected">
  </label>
  <label class="thumb-label">
    {% if user_answer == False %}
      <input type="radio" name="choice" class="thumb-radio" onchange="select_choice(this);" value="down" checked="checked">
    {% else %}
      <input type="radio" name="choice" class="thumb-radio" onchange="select_choice(this);" value="down">
    {% endif %}
    <img src="{% static 'feedback/thumbdown.png' %}" alt="Thumb down">
    <img src="{% static 'feedback/thumbdown_selected.png' %}" alt="Thumb down selected">
  </label>
{% endblock %}